#!/usr/bin/env python3
"""Export FastAPI route inventory to docs/generated.

Default behavior imports app.server:create_app() because it is the safe,
lightweight app-factory surface. To inspect production routes, pass
``--app main:app`` explicitly in a runtime where importing main.py is expected.
"""

from __future__ import annotations

import argparse
import importlib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
DEFAULT_OUTPUT_DIR = ROOT / "docs" / "generated"


def load_app(spec: str) -> Any:
    module_name, _, attr_expr = spec.partition(":")
    if not module_name or not attr_expr:
        raise ValueError("app spec must look like 'module:attribute' or 'module:function()'")
    module = importlib.import_module(module_name)
    if attr_expr.endswith("()"):
        factory_name = attr_expr[:-2]
        factory = getattr(module, factory_name)
        return factory()
    return getattr(module, attr_expr)


def classify_owner(module_name: str, path: str) -> str:
    if module_name.startswith("app.api.nexus"):
        return "nexus-read-only"
    if module_name.startswith("app.api.echo"):
        return "echo-read-only"
    if module_name.startswith("app.api.jobs"):
        return "jobs-router"
    if module_name.startswith("app.api.runtime_controls"):
        return "runtime-controls"
    if module_name.startswith("app.api.audio"):
        return "audio-read-status"
    if module_name.startswith("app.api.model_settings"):
        return "model-settings"
    if module_name.startswith("app.api.system") or module_name.startswith("app.api.health"):
        return "system"
    if module_name == "main" and path.startswith(("/voice", "/tts", "/echo/stream")):
        return "audio-runtime-main"
    if module_name == "main" and path.startswith("/model"):
        return "model-runtime-main"
    if module_name == "main" and path.startswith(("/api/atlas", "/api/plans", "/api/runs", "/agent")):
        return "atlas-main"
    if module_name == "main":
        return "main"
    return "other"


def iter_routes(app: Any) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for route in getattr(app, "routes", []):
        path = getattr(route, "path", None)
        if not path:
            continue
        endpoint = getattr(route, "endpoint", None)
        endpoint_name = getattr(endpoint, "__name__", "") if endpoint else ""
        module_name = getattr(endpoint, "__module__", "") if endpoint else ""
        methods = sorted(getattr(route, "methods", []) or [])
        if not methods and route.__class__.__name__.lower().endswith("websocketroute"):
            methods = ["WEBSOCKET"]
        rows.append(
            {
                "path": path,
                "methods": methods,
                "endpoint_name": endpoint_name,
                "module": module_name,
                "owner": classify_owner(module_name, path),
            }
        )
    return sorted(rows, key=lambda row: (row["path"], row["methods"], row["endpoint_name"]))


def render_markdown(rows: list[dict[str, Any]], app_spec: str) -> str:
    lines = [
        "# Generated FastAPI Route Inventory",
        "",
        "Generated by `scripts/export_route_inventory.py`.",
        "",
        f"App spec: `{app_spec}`",
        "",
        "| path | methods | endpoint name | module | owner分類 |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        methods = ", ".join(row["methods"])
        lines.append(
            f"| `{row['path']}` | `{methods}` | `{row['endpoint_name']}` | "
            f"`{row['module']}` | `{row['owner']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app", default="app.server:create_app()", help="FastAPI app spec")
    parser.add_argument("--out-dir", default=str(DEFAULT_OUTPUT_DIR), help="output directory")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    app = load_app(args.app)
    rows = iter_routes(app)
    (out_dir / "route_inventory.json").write_text(
        json.dumps(rows, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (out_dir / "route_inventory.md").write_text(
        render_markdown(rows, args.app),
        encoding="utf-8",
    )
    print(out_dir / "route_inventory.md")
    print(out_dir / "route_inventory.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
